/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.vistas.datos.pasaporte;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author abnerhl
 */
public class PasaporteGUI extends javax.swing.JPanel {

    /**
     * Creates new form PasaporteGUI
     */
    public PasaporteGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNoPasaporte = new javax.swing.JLabel();
        tflNoPasaporte = new javax.swing.JTextField();
        lblContrasenya = new javax.swing.JLabel();
        tflContrasenya = new javax.swing.JTextField();
        lblFechaNacimiento = new javax.swing.JLabel();
        tflFechaNacimiento = new javax.swing.JTextField();
        lblNacionalidad = new javax.swing.JLabel();
        tflNacionalidad = new javax.swing.JTextField();
        tflNombre = new javax.swing.JTextField();
        lblEstadoCivil = new javax.swing.JLabel();
        tflEstadoCivil = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        tflApellidos = new javax.swing.JTextField();
        lblSexo = new javax.swing.JLabel();
        tflSexo = new javax.swing.JTextField();
        lblApellidos = new javax.swing.JLabel();
        tflFechaEmision = new javax.swing.JTextField();
        lblFechaVencimiento = new javax.swing.JLabel();
        tflFechaVencimiento = new javax.swing.JTextField();
        lvlFechaEmision = new javax.swing.JLabel();
        lblPaisActual = new javax.swing.JLabel();
        tflPaisActual = new javax.swing.JTextField();
        lblMillasRecorridas = new javax.swing.JLabel();
        tflMillasRecorridas = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        lblNoPasaporte.setText("NO. de pasapote:");

        lblContrasenya.setText("Contraseña:");

        lblFechaNacimiento.setText("Fecha de nacimiento (dd/MM/yyyy):");

        lblNacionalidad.setText("Nacionalidad");

        lblEstadoCivil.setText("Estado civil:");

        lblNombre.setText("Nombre:");

        lblSexo.setText("Sexo:");

        lblApellidos.setText("Apellidos:");

        lblFechaVencimiento.setText("Fecha de vencimiento (dd/MM/yyyy):");

        lvlFechaEmision.setText("Fecha de emision (dd/MM/yyyy):");

        lblPaisActual.setText("Pais actual:");

        lblMillasRecorridas.setText("Millas recorridas:");

        btnAgregar.setText("Agregar");

        btnBorrar.setText("Borrar");

        btnActualizar.setText("Actualizar");

        btnLimpiar.setText("Limpiar");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFechaNacimiento)
                            .addComponent(lblNoPasaporte)
                            .addComponent(lblNombre)
                            .addComponent(lblSexo))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(tflFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tflNoPasaporte, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tflNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tflSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblNacionalidad)
                                .addComponent(lblContrasenya, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(lblEstadoCivil)
                            .addComponent(lblApellidos))
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tflEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tflApellidos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tflNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tflContrasenya, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblFechaVencimiento)
                                .addGap(21, 21, 21))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnAgregar)
                                    .addComponent(lblPaisActual))
                                .addGap(127, 127, 127)
                                .addComponent(btnActualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tflFechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(lvlFechaEmision)
                                .addGap(18, 18, 18)
                                .addComponent(tflFechaEmision, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tflPaisActual, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(89, 89, 89)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnBorrar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnLimpiar)
                                        .addGap(12, 12, 12))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblMillasRecorridas)
                                        .addGap(59, 59, 59)
                                        .addComponent(tflMillasRecorridas, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(225, 225, 225))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblNoPasaporte)
                                    .addComponent(lblContrasenya))
                                .addGap(18, 18, 18)
                                .addComponent(lblNacionalidad)
                                .addGap(73, 73, 73)
                                .addComponent(lblEstadoCivil))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tflNoPasaporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tflFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFechaNacimiento))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tflNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNombre))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tflSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSexo)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(tflContrasenya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tflNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tflApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblApellidos))
                        .addGap(18, 18, 18)
                        .addComponent(tflEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFechaVencimiento)
                            .addComponent(tflFechaEmision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tflFechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lvlFechaEmision)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPaisActual)
                        .addComponent(tflMillasRecorridas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblMillasRecorridas)
                    .addComponent(tflPaisActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnBorrar)
                    .addComponent(btnActualizar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblContrasenya;
    private javax.swing.JLabel lblEstadoCivil;
    private javax.swing.JLabel lblFechaNacimiento;
    private javax.swing.JLabel lblFechaVencimiento;
    private javax.swing.JLabel lblMillasRecorridas;
    private javax.swing.JLabel lblNacionalidad;
    private javax.swing.JLabel lblNoPasaporte;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPaisActual;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lvlFechaEmision;
    private javax.swing.JTextField tflApellidos;
    private javax.swing.JTextField tflContrasenya;
    private javax.swing.JTextField tflEstadoCivil;
    private javax.swing.JTextField tflFechaEmision;
    private javax.swing.JTextField tflFechaNacimiento;
    private javax.swing.JTextField tflFechaVencimiento;
    private javax.swing.JTextField tflMillasRecorridas;
    private javax.swing.JTextField tflNacionalidad;
    private javax.swing.JTextField tflNoPasaporte;
    private javax.swing.JTextField tflNombre;
    private javax.swing.JTextField tflPaisActual;
    private javax.swing.JTextField tflSexo;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnActualizar() {
        return btnActualizar;
    }

    public JButton getBtnAgregar() {
        return btnAgregar;
    }

    public JButton getBtnBorrar() {
        return btnBorrar;
    }

    public JButton getBtnLimpiar() {
        return btnLimpiar;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public JTable getjTable1() {
        return jTable1;
    }

    public JLabel getLblApellidos() {
        return lblApellidos;
    }

    public JLabel getLblContrasenya() {
        return lblContrasenya;
    }

    public JLabel getLblEstadoCivil() {
        return lblEstadoCivil;
    }

    public JLabel getLblFechaNacimiento() {
        return lblFechaNacimiento;
    }

    public JLabel getLblFechaVencimiento() {
        return lblFechaVencimiento;
    }

    public JLabel getLblMillasRecorridas() {
        return lblMillasRecorridas;
    }

    public JLabel getLblNacionalidad() {
        return lblNacionalidad;
    }

    public JLabel getLblNoPasaporte() {
        return lblNoPasaporte;
    }

    public JLabel getLblNombre() {
        return lblNombre;
    }

    public JLabel getLblPaisActual() {
        return lblPaisActual;
    }

    public JLabel getLblSexo() {
        return lblSexo;
    }

    public JLabel getLvlFechaEmision() {
        return lvlFechaEmision;
    }

    public JTextField getTflApellidos() {
        return tflApellidos;
    }

    public JTextField getTflContrasenya() {
        return tflContrasenya;
    }

    public JTextField getTflEstadoCivil() {
        return tflEstadoCivil;
    }

    public JTextField getTflFechaEmision() {
        return tflFechaEmision;
    }

    public JTextField getTflFechaNacimiento() {
        return tflFechaNacimiento;
    }

    public JTextField getTflFechaVencimiento() {
        return tflFechaVencimiento;
    }

    public JTextField getTflMillasRecorridas() {
        return tflMillasRecorridas;
    }

    public JTextField getTflNacionalidad() {
        return tflNacionalidad;
    }

    public JTextField getTflNoPasaporte() {
        return tflNoPasaporte;
    }

    public JTextField getTflNombre() {
        return tflNombre;
    }

    public JTextField getTflPaisActual() {
        return tflPaisActual;
    }

    public JTextField getTflSexo() {
        return tflSexo;
    }

    

}
