/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.vistas.datos.avion;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author abnerhl
 */
public class AvionGUI extends javax.swing.JPanel {

    /**
     * Creates new form AvionGUI
     */
    public AvionGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombreAerolinea = new javax.swing.JLabel();
        tflNombreAerolinea = new javax.swing.JTextField();
        lblNombreAeropuertoActual = new javax.swing.JLabel();
        tflNombreAeropuertoActual = new javax.swing.JTextField();
        lblCodigoAvion = new javax.swing.JLabel();
        tflCodigoAvion = new javax.swing.JTextField();
        lblCapacidadPasajeros = new javax.swing.JLabel();
        tflCapacidadPasajeros = new javax.swing.JTextField();
        lblCapacidadGasolina = new javax.swing.JLabel();
        tflCapacidadGasolina = new javax.swing.JTextField();
        tflConsumoPorMilla = new javax.swing.JTextField();
        lblConsumoPorMilla = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatosAviones = new javax.swing.JTable();

        lblNombreAerolinea.setText("Nombre de la aerolinea:");

        lblNombreAeropuertoActual.setText("Nombre del aeropuerto actual:");

        lblCodigoAvion.setText("Codigo del avion:");

        lblCapacidadPasajeros.setText("Capacidad de pasajeros:");

        lblCapacidadGasolina.setText("Capacidad de gasolina:");

        lblConsumoPorMilla.setText("Consumo por milla:");

        btnAgregar.setText("Agregar");

        btnActualizar.setText("Actualizar");

        btnBorrar.setText("Borrar");

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        tblDatosAviones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblDatosAviones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAgregar)
                                .addGap(34, 34, 34)
                                .addComponent(btnActualizar)
                                .addGap(18, 18, 18)
                                .addComponent(btnBorrar)
                                .addGap(33, 33, 33)
                                .addComponent(btnLimpiar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblConsumoPorMilla, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCapacidadGasolina, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCapacidadPasajeros, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCodigoAvion, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblNombreAeropuertoActual)
                                        .addGap(54, 54, 54))
                                    .addComponent(lblNombreAerolinea, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tflNombreAerolinea, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tflNombreAeropuertoActual, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tflCodigoAvion, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tflCapacidadPasajeros, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tflCapacidadGasolina, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tflConsumoPorMilla, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreAerolinea)
                    .addComponent(tflNombreAerolinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreAeropuertoActual)
                    .addComponent(tflNombreAeropuertoActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoAvion)
                    .addComponent(tflCodigoAvion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCapacidadPasajeros)
                    .addComponent(tflCapacidadPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCapacidadGasolina)
                    .addComponent(tflCapacidadGasolina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConsumoPorMilla)
                    .addComponent(tflConsumoPorMilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnActualizar)
                    .addComponent(btnBorrar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCapacidadGasolina;
    private javax.swing.JLabel lblCapacidadPasajeros;
    private javax.swing.JLabel lblCodigoAvion;
    private javax.swing.JLabel lblConsumoPorMilla;
    private javax.swing.JLabel lblNombreAerolinea;
    private javax.swing.JLabel lblNombreAeropuertoActual;
    private javax.swing.JTable tblDatosAviones;
    private javax.swing.JTextField tflCapacidadGasolina;
    private javax.swing.JTextField tflCapacidadPasajeros;
    private javax.swing.JTextField tflCodigoAvion;
    private javax.swing.JTextField tflConsumoPorMilla;
    private javax.swing.JTextField tflNombreAerolinea;
    private javax.swing.JTextField tflNombreAeropuertoActual;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnActualizar() {
        return btnActualizar;
    }

    public JButton getBtnAgregar() {
        return btnAgregar;
    }

    public JButton getBtnBorrar() {
        return btnBorrar;
    }

    public JButton getBtnLimpiar() {
        return btnLimpiar;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public JLabel getLblCapacidadGasolina() {
        return lblCapacidadGasolina;
    }

    public JLabel getLblCapacidadPasajeros() {
        return lblCapacidadPasajeros;
    }

    public JLabel getLblCodigoAvion() {
        return lblCodigoAvion;
    }

    public JLabel getLblConsumoPorMilla() {
        return lblConsumoPorMilla;
    }

    public JLabel getLblNombreAerolinea() {
        return lblNombreAerolinea;
    }

    public JLabel getLblNombreAeropuertoActual() {
        return lblNombreAeropuertoActual;
    }

    public JTable getTblDatosAviones() {
        return tblDatosAviones;
    }

    public JTextField getTflCapacidadGasolina() {
        return tflCapacidadGasolina;
    }

    public JTextField getTflCapacidadPasajeros() {
        return tflCapacidadPasajeros;
    }

    public JTextField getTflCodigoAvion() {
        return tflCodigoAvion;
    }

    public JTextField getTflConsumoPorMilla() {
        return tflConsumoPorMilla;
    }

    public JTextField getTflNombreAerolinea() {
        return tflNombreAerolinea;
    }

    public JTextField getTflNombreAeropuertoActual() {
        return tflNombreAeropuertoActual;
    }

    public void limpiarCampos() {
        getTflNombreAerolinea().setText("");
        getTflNombreAeropuertoActual().setText("");
        getTflCodigoAvion().setText("");
        getTflCapacidadPasajeros().setText("");
        getTflCapacidadGasolina().setText("");
        getTflConsumoPorMilla().setText("");
    }
    

}
